#!/bin/sh

AIRCONNECT_USER="$(echo "${SYNOPKG_PKGNAME}" | awk '{print tolower($_)}')"
LOG="/var/log/${AIRCONNECT_USER}.log"
# Ensure user 'airconnect' exists before doing anything
if ! synouser --get "${AIRCONNECT_USER}" >/dev/null 2>&1; then
    # create user with random password
    echo "[$(date +'%T')] start-stop-status - Creating \"${AIRCONNECT_USER}\" user." >>"$LOG"
    synouser --add "${AIRCONNECT_USER}" "$(uuidgen | cut -c-8)" 'AirConnect User' 0 '' ''
else
    echo "[$(date +'%T')] Securing existing \"${AIRCONNECT_USER}\" user." >>"$LOG"
    synouser --modify "${AIRCONNECT_USER}" 'AirConnect User' 0 ''
fi
if [ -e "${LOG}" ]; then
    chown "${AIRCONNECT_USER}":users "${LOG}"
else
    touch "${LOG}"
    chown "${AIRCONNECT_USER}":users "${LOG}"
fi

echo "[$(date +%Y-%m-%d" "%H:%M:%S)] #### Start postupgrade... ####" >>"$LOG"
sleep 3
echo "[$(date +%Y-%m-%d" "%H:%M:%S)] #### Done postupgrade ####" >>"$LOG"
exit 0
