#!/bin/sh

AIRCONNECT_USER="$(echo "${SYNOPKG_PKGNAME}" | awk '{print tolower($_)}')"
AIRCAST_SELECTION="${pkgwizard_binaries_aircast}"
AIRUPNP_SELECTION="${pkgwizard_binaries_airupnp}"
AIRCAST_ENABLED="${SYNOPKG_PKGDEST}/aircast_enabled"
AIRUPNP_ENABLED="${SYNOPKG_PKGDEST}/airupnp_enabled"
LOG="/var/log/${AIRCONNECT_USER}.log"
# Ensure user 'airconnect' exists before doing anything
if ! synouser --get "${AIRCONNECT_USER}" >/dev/null 2>&1; then
    # create user with random password
    echo "[$(date +'%T')] start-stop-status - Creating \"${AIRCONNECT_USER}\" user." >>"${LOG}"
    synouser --add "${AIRCONNECT_USER}" "$(uuidgen | cut -c-8)" 'AirConnect User' 0 '' ''
else
    echo "[$(date +'%T')] Securing existing \"${AIRCONNECT_USER}\" user." >>"${LOG}"
    synouser --modify "${AIRCONNECT_USER}" 'AirConnect User' 0 ''
fi
if [ -e "${LOG}" ]; then
    chown "${AIRCONNECT_USER}":users "${LOG}"
else
    touch "${LOG}"
    chown "${AIRCONNECT_USER}":users "${LOG}"
fi

echo "[$(date +%Y-%m-%d" "%H:%M:%S)] #### Start preinst... ####" >>"${LOG}"

if [ "${AIRCAST_SELECTION}" == "true" ]; then
    echo "[$(date +'%T')] Using installation type for aircast only" >>"$LOG"
    echo "[$(date +'%T')] Creating airupnp state file \"${AIRCAST_ENABLED}\"..." >>"$LOG"
    touch "${AIRCAST_ENABLED}"
    rm "${AIRUPNP_ENABLED}"
elif [ "${AIRUPNP_SELECTION}" == "true" ]; then
    echo "[$(date +'%T')] Using installation type for airupnp only" >>"$LOG"
    echo "[$(date +'%T')] Creating airupnp state file \"${AIRUPNP_ENABLED}\"..." >>"$LOG"
    touch "${AIRUPNP_ENABLED}"
    rm "${AIRCAST_ENABLED}"
else
    echo "[$(date +'%T')] Using installation type for both binaries (airupnp and aircast)" >>"$LOG"
fi

sleep 3
echo "[$(date +%Y-%m-%d" "%H:%M:%S)] #### Done preinst ####" >>"${LOG}"
exit 0
